"""Add image review fields

Revision ID: 9a7f22020ab8
Revises: 994009cb1bef
Create Date: 2026-09-09 21:43:11.201786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7f22020ab8'
down_revision: Union[str, Sequence[str], None] = '994009cb1bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'images',
        sa.Column(
            'review_status',
            sa.String(length=20),
            nullable=False,
            server_default='pending'
        )
    )
    op.add_column(
        'images',
        sa.Column('review_reason', sa.Text(), nullable=True)
    )
    op.add_column(
        'images',
        sa.Column('reviewed_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'reviewed_at')
    op.drop_column('images', 'review_reason')
    op.drop_column('images', 'review_status')
    # ### end Alembic commands ###
