"""add image embeddings

Revision ID: cef9aff62ac9
Revises: f0a8a1eb4e6e
Create Date: 2026-09-08 00:05:50.105452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "cef9aff62ac9"
down_revision: Union[str, Sequence[str], None] = "f0a8a1eb4e6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "embedding",
            Vector(768),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "embedding")
    # ### end Alembic commands ###